//! Parity tests: Rust render output must equal the Python laya-mlx output
//! stored in `fixtures/` (generated by `tools/gen_fixtures.py` — that script
//! is the only thing allowed to change expected ids).
//!
//! * `hermetic_parity` — always runs. Hermetic WordLevel tokenizer vendored
//!   in fixtures; no network, no HF cache.
//! * `real_model_parity` — runs only when `LAYA_HF_CACHE` points at a
//!   Hugging Face hub cache holding the `aac6fef` Laya snapshots. Exercises
//!   the real BPE tokenizers (english + multilingual) and per-model budgets.

use std::collections::HashMap;
use std::path::{Path, PathBuf};

use jevalaya_render::LayaTokenizer;
use serde_json::Value;

fn fixtures_root() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("fixtures")
}

fn load_json(path: &Path) -> Value {
    let text =
        std::fs::read_to_string(path).unwrap_or_else(|e| panic!("read {}: {e}", path.display()));
    serde_json::from_str(&text).unwrap_or_else(|e| panic!("parse {}: {e}", path.display()))
}

fn as_u32_vec(v: &Value) -> Vec<u32> {
    v.as_array()
        .expect("expected array")
        .iter()
        .map(|x| x.as_u64().expect("expected int") as u32)
        .collect()
}

/// Rebuild every item in one fixture file and diff against Python's ids.
fn check_fixture_file(path: &Path, tok: &LayaTokenizer, checked: &mut usize) {
    let fx = load_json(path);
    let max_len = fx["max_len"].as_u64().expect("max_len") as usize;
    let head_max_len = fx["head_max_len"].as_u64().expect("head_max_len") as usize;

    // The loader must resolve the same special ids Python recorded.
    let sp = &fx["specials"];
    assert_eq!(
        tok.cls_id() as u64,
        sp["cls_token_id"].as_u64().unwrap(),
        "cls id {path:?}"
    );
    assert_eq!(
        tok.sep_id() as u64,
        sp["sep_token_id"].as_u64().unwrap(),
        "sep id {path:?}"
    );
    assert_eq!(
        tok.pad_id() as u64,
        sp["pad_token_id"].as_u64().unwrap(),
        "pad id {path:?}"
    );
    assert_eq!(
        tok.mask_id() as u64,
        sp["mask_token_id"].as_u64().unwrap(),
        "mask id {path:?}"
    );

    let questions = fx["questions"].as_object().expect("questions object");
    let got = jevalaya_render::prepare(tok, &fx["state"], questions, max_len, head_max_len)
        .unwrap_or_else(|e| panic!("prepare {path:?}: {e}"));
    let mut by_qid: HashMap<&str, _> = HashMap::new();
    for (qid, rendered) in &got {
        by_qid.insert(qid.as_str(), rendered);
    }
    // input_tokens parity: Python usage counts sum(len(ids)).
    let mut input_tokens = 0;
    for item in fx["items"].as_array().expect("items") {
        let qid = item["qid"].as_str().unwrap();
        let rendered = by_qid
            .remove(qid)
            .unwrap_or_else(|| panic!("missing {qid} in {path:?}"));
        assert_eq!(
            rendered.ids,
            as_u32_vec(&item["ids"]),
            "ids mismatch qid={qid} file={path:?}"
        );
        assert_eq!(
            rendered.markers,
            as_u32_vec(&item["markers"]),
            "markers mismatch qid={qid} file={path:?}"
        );
        assert_eq!(
            rendered.qtype as u64,
            item["qtype"].as_u64().unwrap(),
            "qtype mismatch qid={qid} file={path:?}"
        );
        // Pre-truncation gate counts must match Python's raw_count; the
        // execution ids above must never feed the ANE gate.
        let question = jevalaya_render::to_internal(&questions[qid])
            .unwrap_or_else(|e| panic!("to_internal {qid} in {path:?}: {e}"));
        for alignment in [1usize, 8usize] {
            let gc =
                jevalaya_render::gate_counts(tok, &fx["state"], &question, head_max_len, alignment)
                    .unwrap_or_else(|e| panic!("gate_counts {qid} in {path:?}: {e}"));
            assert_eq!(
                gc.raw_count as u64,
                item["raw_count"].as_u64().unwrap(),
                "raw_count mismatch qid={qid} file={path:?}"
            );
            assert_eq!(
                gc.aligned_count,
                gc.raw_count.div_ceil(alignment) * alignment,
                "aligned_count mismatch qid={qid} file={path:?}"
            );
            // Execution (post-truncation) length can only undercut raw.
            assert!(
                rendered.ids.len() <= gc.raw_count,
                "exec longer than raw qid={qid} file={path:?}"
            );
        }
        input_tokens += rendered.ids.len();
        *checked += 1;
    }
    assert!(by_qid.is_empty(), "extra questions rendered in {path:?}");
    let _ = input_tokens;
}

#[test]
fn hermetic_parity() {
    let root = fixtures_root();
    let tok = LayaTokenizer::from_tokenizer_dir(&root.join("hermetic/tokenizer"))
        .expect("load hermetic tokenizer");
    let mut files: Vec<PathBuf> = glob::glob(root.join("hermetic/*/*.json").to_str().unwrap())
        .expect("glob")
        .filter_map(Result::ok)
        .filter(|p| !p.to_string_lossy().contains("/tokenizer/"))
        .collect();
    files.sort();
    assert!(!files.is_empty(), "no hermetic fixtures found");
    let mut checked = 0;
    for path in &files {
        check_fixture_file(path, &tok, &mut checked);
    }
    eprintln!(
        "hermetic parity: {} files, {} questions, all ids/markers/qtype equal",
        files.len(),
        checked
    );
    assert!(checked > 0);
}

#[test]
fn loader_rejects_missing_special_like_python() {
    // A tokenizer dir whose config lacks mask_token must fail loudly,
    // mirroring Python's `ValueError("Tokenizer is missing a valid ...")`.
    let root = fixtures_root();
    let dir = std::env::temp_dir().join("jevalaya-render-bad-tok");
    let _ = std::fs::remove_dir_all(&dir);
    std::fs::create_dir_all(&dir).unwrap();
    std::fs::copy(
        root.join("hermetic/tokenizer/tokenizer.json"),
        dir.join("tokenizer.json"),
    )
    .unwrap();
    std::fs::write(
        dir.join("tokenizer_config.json"),
        r#"{"pad_token": "[PAD]", "cls_token": "[CLS]", "sep_token": "[SEP]"}"#,
    )
    .unwrap();
    let err = LayaTokenizer::from_tokenizer_dir(&dir)
        .unwrap_err()
        .to_string();
    assert!(err.contains("mask_token"), "unexpected error: {err}");
    let _ = std::fs::remove_dir_all(&dir);
}

#[test]
fn real_model_parity() {
    let cache = match std::env::var("LAYA_HF_CACHE") {
        Ok(v) => PathBuf::from(v),
        Err(_) => {
            eprintln!("SKIP real_model_parity: set LAYA_HF_CACHE=<hf hub cache> to run");
            return;
        }
    };
    // model name in fixture -> hub cache dir name
    let hub_dirs = [
        ("english", "models--aac6fef--laya-mlx"),
        ("multilingual", "models--aac6fef--laya-multilingual-mlx"),
    ];
    let root = fixtures_root();
    let mut files: Vec<PathBuf> = glob::glob(root.join("real/*.json").to_str().unwrap())
        .expect("glob")
        .filter_map(Result::ok)
        .collect();
    files.sort();
    assert!(!files.is_empty(), "no real fixtures found");
    let mut checked = 0;
    for path in &files {
        let fx = load_json(path);
        let model = fx["model"].as_str().unwrap().to_string();
        let hub = hub_dirs
            .iter()
            .find(|(m, _)| *m == model)
            .unwrap_or_else(|| panic!("unknown model {model} in {path:?}"));
        let snaps: Vec<PathBuf> =
            glob::glob(cache.join(hub.1).join("snapshots/*").to_str().unwrap())
                .expect("glob")
                .filter_map(Result::ok)
                .collect();
        assert!(!snaps.is_empty(), "no cached snapshot for {model}");
        let tok = LayaTokenizer::from_tokenizer_dir(&snaps[0].join("tokenizer"))
            .unwrap_or_else(|e| panic!("load {model} tokenizer: {e}"));
        check_fixture_file(path, &tok, &mut checked);
    }
    eprintln!(
        "real-model parity: {} files, {} questions equal",
        files.len(),
        checked
    );
    assert!(checked > 0);
}
